version: "3.8"

services:
  tuya-exporter:
    build: ./tuya-exporter
    container_name: tuya-exporter
    ports:
      - "9109:9109"
    environment:
      TUYA_ACCESS_ID: "3jp9pupyd4uy3rf3t7wr"
      TUYA_ACCESS_SECRET: "74d3222c33f245a4958d5bf019eec35a"
      TUYA_ENDPOINT: "https://openapi.tuyain.com"
    restart: unless-stopped


